version: '2.1'

services:
  prometheus:
    image: prom/prometheus:v2.7.2
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.no-lockfile'
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention.size=512MB'
    ports:
      - 9090:9090
    restart: always
    networks:
      - promnet


  alertmanager:
    image: prom/alertmanager:v0.11.0
    volumes:
      - ./config:/prometheus
      - ./data/alertmanager:/data
    command:
      - '-config.file=/prometheus/alertmanager.yml'
      - '-storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - promnet

  alerta:
    image: alerta/alerta-web
    ports:
      - 9080:8080
    depends_on:
      - db
    environment:
      - AUTH_REQUIRED=${AUTH_REQUIRED:-False}
      - ADMIN_USERS=${ADMIN_USERS:-not-set}
      - CUSTOMER_VIEWS=${CUSTOMER_VIEWS:-False}
      - PROVIDER=${PROVIDER:-basic}
      - CLIENT_ID=${CLIENT_ID:-not-set}
      - CLIENT_SECRET=${CLIENT_SECRET:-not-set}
      - ALLOWED_EMAIL_DOMAIN=${ALLOWED_EMAIL_DOMAIN:-*}
      - ALLOWED_GITHUB_ORGS=${ALLOWED_GITHUB_ORGS:-*}
      - GITLAB_URL=${GITLAB_URL:-not-set}
      - ALLOWED_GITLAB_GROUPS=${ALLOWED_GITLAB_GROUPS:-*}
      - INSTALL_PLUGINS=slack,prometheus
      - PLUGINS=${PLUGINS:-reject,prometheus}
      - ALERTMANAGER_API_URL=http://alertmanager:9093
      - ORIGIN_BLACKLIST=${ORIGIN_BLACKLIST:-not-set}
      - ALLOWED_ENVIRONMENTS=${ALLOWED_ENVIRONMENTS:-Production,Development}
      - MONGO_URI=mongodb://db:27017/monitoring
    restart: always
    networks:
      - promnet
      - dbnet

  db:
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    restart: always
    networks:
      - dbnet

networks:
  promnet:
    driver: bridge
  dbnet:
    driver: bridge

