---
- name: Include basic vars for localhost hosts
  hosts: localhost
  tasks:
    - name: Include variables
      include_vars: vars/main.yaml

- name: Create instances
  hosts: localhost
  roles:
#    - role: create_os_resources
#      tags: ['init-base-os-resources']
#
    - role: create_os_resources
      tags: ['master']
      vars:
        group: 'master'
        instance_count: 1
        instance_name: 'prometheus-master'
        assign_floating_ip: true

    - role: create_os_resources
      tags: ['slaves-daemon-set']
      vars:
        group: 'slaves-daemon-set'
        instance_name: 'prometheus-slave'
        assign_floating_ip: true

    - role: create_os_resources
      tags: ['slaves-general-load']
      vars:
        group: 'slaves-general-load'
        instance_count: 1
        instance_name: 'prometheus-slave'
        assign_floating_ip: false

- name: Include basic vars for all hosts
  hosts: all
  tasks:
  - name: Include variables
    include_vars: vars/main.yaml

- name: Deploy monitoring master machine
  hosts: master
  become_user: root
  become: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  roles:
    - { role: common }
    - { role: squid }
    - { role: docker }
    - { role: docker_compose }

#- name: Deploy daemon set slaves
#  hosts: slaves-daemon-set
#  become_user: root
#  become: yes
#  environment:
#    http_proxy: "{{ http_proxy }}"
#    https_proxy: "{{ http_proxy }}"
#  roles:
#    - { role: common }

- name: Deploy workload slaves
  hosts: slaves-general-load
  become_user: root
  become: yes
#  environment:
#    http_proxy: "{{ hostvars[master_instance_ip]['private_ip'] }}"
#    https_proxy: "{{ hostvars[master_instance_ip]['private_ip'] }}"
#    http_proxy: "{{ http_proxy }}"
#    https_proxy: "{{ http_proxy }}"
  roles:
  - { role: common }
