- hosts: all
  vars:
  remote_user: user
  become: yes
  
  tasks:
    - name: Create a new instance and attaches to a network and passes metadata to the instance
      os_server:
           state: present
           auth:
             auth_url: http://10.147.204.76:35357/v3
             username: admin
             password: fDMBVaSmcgp1TzGJ
             project_name: mons
           name: vm1
           image: 4f905f38-e52a-43d2-b6ec-754a13ffb529
           key_name: ansible_key
           timeout: 200
           flavor: 4
           nics:
             - net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
             - net-name: another_network
           meta:
             hostname: test1
             group: uge_master
