- name: Retrieve all available Openstack hypervisors
  os_hypervisor_facts:
    enabled: True
    active: True
    validate_certs: no

- name: Create new instance with prometheus, alert manager and alerta
  register: "os_hosts"
  os_server:
    state: present
    timeout: 200
    name: "{{ instance_name }}-{{ item.name.split('.')[0] }}"
    cloud: "{{ cloud }}"
    image: "{{ image_id }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_id }}"
    security_groups: "{{ security_groups }}"
    # TODO (msenin): make it random (?)
    floating_ip_pools: "{{ floating_ip_pools if assign_floating_ip == true else omit }}"
    nics: [ net-id: "{{ net_id }}" ]
    validate_certs: no
    userdata: "{{ cloudinit }}"
    availability_zone: "{{ availability_zone }}:{{ item.name.split('.')[0] }}"
    meta:
      hostname: "{{ instance_name }}"
      group: "{{ group }}"
  loop: "{{ openstack_hypervisor | flatten(levels=1) }}"

- name: Add hosts to inventory
  add_host:
    name: "{{ item['server']['public_v4'] }}"
    ansible_user: "{{ instance_manage_user }}"
    groups: "{{ group }}"
    instance_name: "{{ item['server']['name'] }}"
    ansible_host: "{{ item['server']['public_v4'] }}"
  loop: "{{ os_hosts.results }}"

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: "{{ waiter_timeout }}"
